name: workspace

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  docker:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: pwd
        run: |
          pwd

      - name: ls
        run: |
          ls

      - name: Docstring Auditor
        uses: agencyenterprise/docstring-auditor@latest
        with:
          openaiApiKey: ${{ secrets.OPENAI_API_KEY }}
          path: docstring_auditor
